# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dfe186df5c1666d4a3d44dcaab4b32f6"
name = "recovery-cart"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_themes,write_metaobject_definitions,read_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[shop.metafields.app.settings]
type = "json"
name = "Recovery cart"

  [shop.metafields.app.settings.access]
  storefront = "public_read"

[build]
automatically_update_urls_on_dev = true
