# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4532fcfd39a7d4ad6c44f184d0226dd"
name = "Recovery Cart"
application_url = "https://recovery-cart.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
# Use the latest stable Admin API version for webhooks.
# Check https://shopify.dev/docs/api/admin-graphql for current versions.
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "https://recovery-cart.vercel.app/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "https://recovery-cart.vercel.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
 compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "https://recovery-cart.vercel.app/webhooks"

[access_scopes]
# Learn more at
# https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# write_products: Required for product management
# read_metaobject_definitions, write_metaobject_definitions: Required for metaobjects
scopes = "write_products,read_metaobject_definitions,write_metaobject_definitions,read_themes"

[auth]
redirect_urls = ["https://recovery-cart.vercel.app/api/auth"]

[shop.metafields.app.settings]
type = "json"
name = "Recovery cart"


  [shop.metafields.app.settings.access]
  storefront = "public_read"
